/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.ShapesDAO;
import Models.Shape;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JPanel;

/**
 *
 * @author juanc
 */
public class MainPanel extends JPanel{
    ShapesDAO shapes;
    Helper helper;
    Shape shape;
    Image image;
    int mode;
    /**
     * Creates new form MainPanel
     */
    public MainPanel(ShapesDAO shapes) {
        initComponents();
        this.setBounds(100, 80, 800, 700);
        this.shapes = shapes;
        mode = 0;
    }

    public void setShape(Shape shape) {
        this.shape = shape;
    }

    public void setMode(int mode) {
        this.mode = mode;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        helper = new Helper(g);
        helper.drawImage(image);
        helper.draw(shapes);
        if (mode == 1)
            helper.drawSimple(shape);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
