/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.ShapesDAO;
import java.awt.Dimension;
import java.awt.Label;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author juanc
 */
public class MainWindow extends JFrame{
    MainPanel panel;
    ShapesDAO shapes;
    /**
     * Creates new form MainWindow
     */
    
    public MainWindow(ShapesDAO shapes) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/4-this.getSize().width/4,100); 
        this.shapes = shapes;
        this.setTitle("Taller 1 - Juan Cuero");
    }
    
   public void setFilterFile() {
       FileNameExtensionFilter filterImage = new FileNameExtensionFilter("Images", "jpg", "png");
       jFileChooser1.setFileFilter(filterImage);
       
       FileNameExtensionFilter filterJSON = new FileNameExtensionFilter("JSON", "json");
       jFileChooser2.setFileFilter(filterJSON);
      
       jFileChooser3.setFileFilter(filterJSON);
   }

    public void setPanel() {
        panel = new MainPanel(shapes);
        this.add(panel);
        this.setSize(1200, 900);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jFileChooser3 = new javax.swing.JFileChooser();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tipoFigura = new javax.swing.JComboBox<>();
        tipoColor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton10.setText("Cargar imagen");
        getContentPane().add(jButton10);
        jButton10.setBounds(980, 300, 130, 23);

        jButton11.setText("Guardar figuras");
        getContentPane().add(jButton11);
        jButton11.setBounds(980, 450, 130, 23);

        jButton12.setText("Cargar figuras");
        getContentPane().add(jButton12);
        jButton12.setBounds(980, 380, 130, 23);

        jLabel1.setText("Figura:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(980, 60, 90, 14);

        jLabel2.setText("Color:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(980, 160, 120, 14);

        tipoFigura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Figura", "Cuadrado", "Rectangulo", "Circulo", "Elipse", "Linea" }));
        tipoFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoFiguraActionPerformed(evt);
            }
        });
        getContentPane().add(tipoFigura);
        tipoFigura.setBounds(980, 100, 140, 20);

        tipoColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Color", "Verde", "Azul", "Amarillo", "Rojo" }));
        getContentPane().add(tipoColor);
        tipoColor.setBounds(980, 200, 140, 20);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Juan Cuero - juan.cuero@unillanos.edu.co");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(900, 520, 260, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoFiguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoFiguraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFileChooser jFileChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> tipoColor;
    private javax.swing.JComboBox<String> tipoFigura;
    // End of variables declaration//GEN-END:variables



    public JButton getjButton10() {
        return jButton10;
    }

    public JButton getjButton11() {
        return jButton11;
    }

    public JButton getjButton12() {
        return jButton12;
    }

    public MainPanel getPanel() {
        return panel;
    }

    public JFileChooser getjFileChooser1() {
        return jFileChooser1;
    }

    public JFileChooser getjFileChooser2() {
        return jFileChooser2;
    }

    public JFileChooser getjFileChooser3() {
        return jFileChooser3;
    }
    
    public JComboBox gettipoFigura() {
        return tipoFigura;
    }
    
    public JComboBox gettipoColor() {
        return tipoColor;
    }
}
